# Generated by Django 3.1.2 on 2020-10-23 13:31

from django.db import migrations
from django.contrib.auth.admin import User
from restApi.models import Articles


def create_superuser(apps, schema_editor):
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = 'admin'
    superuser.email = 'admin@admin.com'
    superuser.set_password('123')
    superuser.save()

    mock_article = Articles()
    mock_article.title = "HUAWEI Mate40 Series Online Global Launch Event"
    mock_article.image1_url = "https://consumer-img.huawei.com/content/dam/huawei-cbg-site/common/mkt/" + \
                              "pdp/phones/mate40-pro-plus/images/security/unlock/n-plus.jpg"
    mock_article.image2_url = "https://consumer-img.huawei.com/content/dam/huawei-cbg-site/common/mkt/" + \
                              "pdp/phones/mate40-pro-plus/images/photo/portrait/intro/n.jpg"
    mock_article.video_link = "https://youtu.be/oH7H4wnjeYA"
    mock_article.content = ' <iframe width="900" height="506" src="https://www.youtube.com/embed/oH7H4wnjeYA" ' + \
                           'frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media;' + \
                           'gyroscope; picture-in-picture" allowfullscreen></iframe>'
    mock_article.author = superuser
    mock_article.lang = "en"
    mock_article.save()


class Migration(migrations.Migration):
    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
