# Generated by Django 3.1.2 on 2020-10-23 13:31

from django.db import migrations, models
from django.contrib.auth.admin import User


def create_superuser(apps, schema_editor):
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = 'admin'
    superuser.email = 'admin@admin.com'
    superuser.set_password('123')
    superuser.save()

    article = apps.get_model("restApi", "articles")
    user = apps.get_model('auth', 'User')
    admin = user.objects.get(id=1)

    en = article(title="HUAWEI Mate40 Series Online Global Launch Event",
                 image1_url="https://consumer-img.huawei.com/content/dam/huawei-cbg-site/common/mkt/" + \
                            "pdp/phones/mate40-pro-plus/images/security/unlock/n-plus.jpg",
                 image2_url="https://consumer-img.huawei.com/content/dam/huawei-cbg-site/common/mkt/" + \
                            "pdp/phones/mate40-pro-plus/images/photo/portrait/intro/n.jpg",
                 video_link="https://youtu.be/oH7H4wnjeYA",
                 content=' <iframe width="900" height="506" src="https://www.youtube.com/embed/oH7H4wnjeYA" ' + \
                         'frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media;' + \
                         'gyroscope; picture-in-picture" allowfullscreen></iframe>',
                 lang="en",
                 category="General",
                 author=admin)
    en.save()
    tr = article(title="HUAWEI Mate40 Serisi Çevrimiçi Küresel Lansman Etkinliği",
                 image1_url="https://consumer-img.huawei.com/content/dam/huawei-cbg-site/common/mkt/" + \
                            "pdp/phones/mate40-pro-plus/images/security/unlock/n-plus.jpg",
                 image2_url="https://consumer-img.huawei.com/content/dam/huawei-cbg-site/common/mkt/" + \
                            "pdp/phones/mate40-pro-plus/images/photo/portrait/intro/n.jpg",
                 video_link="https://youtu.be/oH7H4wnjeYA",
                 content=' <iframe width="900" height="506" src="https://www.youtube.com/embed/oH7H4wnjeYA" ' + \
                         'frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media;' + \
                         'gyroscope; picture-in-picture" allowfullscreen></iframe>',
                 lang="tr",
                 category="General",
                 author=admin)
    tr.save()


class Migration(migrations.Migration):
    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
